This update gets the logger working in node 0.8.
Prior to this update, the logger was causing the error
TypeError: Object.prototype.__defineGetter__: Expecting function